name: Build and Publish latest image
on:
    push:
        branches: [master]

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build and push Docker images
              uses: docker/build-push-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  repository: syntaxhacker/stayhut
                  tags: latest
            - name: Publish image to Github Packages
              uses: docker/build-push-action@v1
              with:
                  username: $GITHUB_ACTOR
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com
                  repository: syntaxhacker/stayhut/stayhut
                  tag_with_ref: true
                  tag_with_sha: true
            # - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
            #   with:
            #       heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            #       heroku_app_name: "stayhut" #Must be unique in Heroku
            #       heroku_email: "jrohit072@gmail.com"
            #       usedocker: true
